### ISSUE TITLE
Why is there no support for Windows platform?

### ISSUE THREAD

**Issue by charlesgwaldman** [conda-forge/open3d-feedstock#5]
### Comment:

The open3d-admin repo has packages for all 3 platforms (Linux, Mac, Win) but is unusable because it's stuck on python3.9

The `open3d` in `conda-forge` supports python3.11 but there's no Windows package.  What is the barrier to providing one?

**Comment by Tobias-Fischer** [comment]
The barrier is likely just bandwidth by the maintainers (one of them being me). I personally don’t use Windows, so I didn’t put any effort in to get it to work. Feel free to create a pull request to add Windows support, it might work without issues, we just haven’t tried.

**Comment by Tobias-Fischer** [comment]
Fixed in #14
